pipeline {
    agent { label 'kavya' }

    environment {
        project = 'expense'
        component = 'backend'
        deploy_to = 'production'
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters {
        choice(name: 'action',
               choices: ['apply', 'destroy'],
               description: 'Select Terraform action')
    }

    stages {

        stage('Terraform Init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                        cd 50-ecr
                        terraform init
                        """
                    }
                }
            }
        }

        stage('Terraform Apply/Destroy') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                        cd 50-ecr
                        terraform ${params.action} -auto-approve
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed'
            deleteDir()
        }

        success {
            echo 'Pipeline succeeded'
        }

        failure {
            echo 'Pipeline failed'
        }
    }
}