pipeline {
    agent { label 'kavya' }

    environment {
        project = 'expense'
        environment_name = 'dev'
        deploy_to = 'prod'
    }

    options {
        disableConcurrentBuilds()
        ansiColor('xterm')
        timeout(time: 30, unit: 'MINUTES')
    }

    parameters {
        choice(
            name: 'action',
            choices: ['apply', 'destroy'],
            description: 'pick something'
        )
    }

    stages {

        stage('Init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                         cd 40-eks
                        rm -rf .terraform
                        rm -f .terraform.lock.hcl

                           
                            terraform init
                        """
                    }
                }
            }
        }

        stage('Apply') {
            when {
                expression { params.action == 'apply' }
            }
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 40-eks
                            terraform  apply -auto-approve
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'I will run always hello again'
            deleteDir()
        }

        success {
            echo 'I will run when pipeline is success'
        }

        failure {
            echo 'I will run when pipeline is failed'
        }
    }
}