pipeline {
    agent { label  'Agent-1'}
    environment {
        PROJECT='ROBOSHOP'
        ENVIRONMENT='QA'
        DEPLOY_TO='production'
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

parameters{
    choice(name: 'Action', choices: ['apply', 'destroy'],  description: 'pick something')
}
stages {
        stage('Init') {
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan
                    """
                }
                 
               }
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform apply -auto-approve
                    """
                }
                 
               }
            }
        }
        stage('Trigger sg') {
            when {
                expression  { params.Action == 'apply'}
            }
            steps{
                build job: '10-sg', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
            }
        }
}
  post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}
