pipeline {
    agent { label  'kavya'}
    environment {
        project='expense'
        component='backend'
        deploy_to='production'
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters{
        choice( name: 'action', choices: [ 'apply'  ,'destroy'], description: 'pick something')
    }

stages {
        stage('Init') {
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan
                    """
                }
                 
               }
            }
        }
        stage('Apply') {
            
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform ${ params.action } -auto-approve
                    """
                }
                 
               }
            }
        }


        stage('Parallel Stages') {
            when { 
                expression { params.action == 'apply'}
            }
            parallel {
                stage('20-bastion') {    
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'action', value: 'apply')], wait: false
                    }
                }
                stage('30-rds') {
                    steps {
                        build job: '30-rds', parameters: [string(name: 'action', value: 'apply')], wait: false
                    }
                }
                stage('40-eks') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'action', value: 'apply')], wait: false
                    }
                }
                stage('50-ecr') {
                    steps {
                        build job: '50-ecr', parameters: [string(name: 'action', value: 'apply')], wait: false
                    }
                }
            }
        }


        stage('Sequential') {
            stages {
                stage('60-acms') {
                    steps {
                        build job: '60-acms', parameters: [string(name: 'action', value: 'apply')], wait: false
                    }
                }
                stage('70-ingress-alb') {
                    steps {
                        build job: '70-ingress-alb', parameters: [string(name: 'action', value: 'apply')], wait: false
                    }
                }
            }
        }
}
  post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}

