pipeline {
    agent { label  'kavya'}
    environment {
       project='expense'
       component= 'backend'
       deploy_to = 'production'
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters{
        choices (name: 'action',
        choice: ['apply' , 'destroy']
        description: 'pick something')
    }
stages {
        stage('Init') {
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 20-bastion
                        terraform init -reconfigure
                        terraform plan
                    """
                }
                 
               }
            }
        }
        stage('Apply') {
            
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 20-bastion
                        terraform apply -auto-approve
                    """
                }
                 
               }
            }
        }
}
  post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}
